# etcd cluster: 172.21.0.11, 172.21.0.12, 172.21.0.13
# node port: 12379, 22379, 32379

networks:
  etcd-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd1
    ports:
      - "12379:2379"
      - "12380:2380"
    networks:
      etcd-net:
        ipv4_address: 172.21.0.11 
    volumes:
      - $HOME/data/etcd-cluster-without-tls/etcd1:/var/lib/etcd
    command:
      - /usr/local/bin/etcd
      - --name=etcd1
      - --data-dir=/var/lib/etcd
      - --advertise-client-urls=http://172.21.0.11:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://172.21.0.11:2380
      - --initial-cluster=etcd1=http://172.21.0.11:2380,etcd2=http://172.21.0.12:2380,etcd3=http://172.21.0.13:2380
      - --initial-cluster-token=etcd-cluster-test
      - --initial-cluster-state=new
      - --snapshot-count=10000
      - --experimental-initial-corrupt-check=true
      # - --experimental-watch-progress-notify-interval=5s  
      # TLS
      # - --cert-file=/etc/kubernetes/pki/etcd/server.crt
      # - --key-file=/etc/kubernetes/pki/etcd/server.key
      # - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
      # - --client-cert-auth=true
      # - --peer-cert-file=/etc/kubernetes/pki/etcd/server.crt
      # - --peer-key-file=/etc/kubernetes/pki/etcd/server.key
      # - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
      # - --peer-client-cert-auth=true

  etcd2:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd2
    ports:
      - "22379:2379"
      - "22380:2380"
    networks:
      etcd-net:
        ipv4_address: 172.21.0.12 
    volumes:
      - $HOME/data/etcd-cluster-without-tls/etcd2:/var/lib/etcd
      # - ./certs:/etc/kubernetes/pki/etcd:ro
    command:
      - /usr/local/bin/etcd
      - --name=etcd2
      - --data-dir=/var/lib/etcd
      - --advertise-client-urls=http://172.21.0.12:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://172.21.0.12:2380
      - --initial-cluster=etcd1=http://172.21.0.11:2380,etcd2=http://172.21.0.12:2380,etcd3=http://172.21.0.13:2380
      - --initial-cluster-token=etcd-cluster-test
      - --initial-cluster-state=new
      - --snapshot-count=10000
      - --experimental-initial-corrupt-check=true
      # - --experimental-watch-progress-notify-interval=5s  
      # TLS
      # - --cert-file=/etc/kubernetes/pki/etcd/server.crt
      # - --key-file=/etc/kubernetes/pki/etcd/server.key
      # - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
      # - --client-cert-auth=true
      # - --peer-cert-file=/etc/kubernetes/pki/etcd/server.crt
      # - --peer-key-file=/etc/kubernetes/pki/etcd/server.key
      # - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
      # - --peer-client-cert-auth=true

  etcd3:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd3
    ports:
      - "32379:2379"
      - "32380:2380"
    networks:
      etcd-net:
        ipv4_address: 172.21.0.13 
    volumes:
      - $HOME/data/etcd-cluster-without-tls/etcd3:/var/lib/etcd
      # - ./certs:/etc/kubernetes/pki/etcd:ro
    command:
      - /usr/local/bin/etcd
      - --name=etcd3
      - --data-dir=/var/lib/etcd
      - --advertise-client-urls=http://172.21.0.13:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://172.21.0.13:2380
      - --initial-cluster=etcd1=http://172.21.0.11:2380,etcd2=http://172.21.0.12:2380,etcd3=http://172.21.0.13:2380
      - --initial-cluster-token=etcd-cluster-test
      - --initial-cluster-state=new
      - --snapshot-count=10000
      - --experimental-initial-corrupt-check=true
      # - --experimental-watch-progress-notify-interval=5s  
      # TLS
      # - --cert-file=/etc/kubernetes/pki/etcd/server.crt
      # - --key-file=/etc/kubernetes/pki/etcd/server.key
      # - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
      # - --client-cert-auth=true
      # - --peer-cert-file=/etc/kubernetes/pki/etcd/server.crt
      # - --peer-key-file=/etc/kubernetes/pki/etcd/server.key
      # - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
      # - --peer-client-cert-auth=true
