services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    ports:
      - "2379:2379"  # client port 
      - "2380:2380"  # node connect
    volumes:
      - $HOME/data/etcd-single:/var/lib/etcd
    command: >
      /usr/local/bin/etcd
      --name etcd-single
      --data-dir /var/lib/etcd
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://172.21.0.2:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://172.21.0.2:2380
      --initial-cluster my-etcd=http://172.21.0.2:2380
      --initial-cluster-token my-etcd-token
      --initial-cluster-state new
